// generated by stringer -type=Event data.go; DO NOT EDIT

package udp

import "fmt"

const _Event_name = "EventNoneEventStartedEventStoppedEventCompleted"

var _Event_index = [...]uint8{0, 9, 21, 33, 47}

func (i Event) String() string {
	if i < 0 || i >= Event(len(_Event_index)-1) {
		return fmt.Sprintf("Event(%d)", i)
	}
	return _Event_name[_Event_index[i]:_Event_index[i+1]]
}
